### ISSUE TITLE
Introduce a way of flagging data as not ready for publishing

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/everypolitician-data#29]
Currently the publish process simply takes all `final.json` files and submits them to https://huboard.com/mysociety/popolo-viewer-sinatra — but these may not be ready for display yet. There should be a way of flagging each directory as publishable or not.

**Comment by davewhiteland** [comment]
+1 this -- I think ability to mark data as not ready to publish might encourage contributors who might otherwise not be bold enough to submit the data (e.g., just trying it?)
